GET http://localhost:3300/api/post/ab04593b-da99-4fe3-8b4b-e06d82e2efdd/comments

###
# Создание комментария
POST http://localhost:3300/api/post/ab04593b-da99-4fe3-8b4b-e06d82e2efdd/comments
Content-Type: application/json

{
    "text": "Testsdfsdfsdfsdfsd"
}

###

# Удаление комментария
DELETE http://localhost:3300/api/post/ab04593b-da99-4fe3-8b4b-e06d82e2efdd/comments/6a8aa59446a019ac22038648