POST http://localhost:3300/api/post
Content-Type: application/json

{
  "typePost": "VIDEO",
  "title": "Очень интересное видео о разработке",
  "url": "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
  "tags": [
    "nestjs",
    "typescript",
    "backend"
  ]
}
###

GET http://localhost:3300/api/post?page=1&limit=25&sort=mostLiked
###
GET http://localhost:3300/api/post/b915f92b-d452-425e-9e0d-a643eee24beb
###
DELETE http://localhost:3300/api/post/ab04593b-da99-4fe3-8b4b-e06d82e2efdd

###
POST http://localhost:3300/api/post
Content-Type: application/json

{
 "typePost": "TEXT",
 "title": "Как правильно изучать NestJS",
  "preview": "В этой публикации разберём основные возможности NestJS и архитектуру серверного приложения.",
  "text": "NestJS предоставляет модульную архитектуру, dependency injection, контроллеры, providers, pipes, guards и interceptors. Благодаря этому приложение проще тестировать и расширять.",
  "tags": [
    "nestjs",
    "nodejs"
  ]
}

###
POST http://localhost:3300/api/post
Content-Type: application/json

{
  "typePost": "LINK",
  "link": "https://nestjs.com",
  "description": "Официальный сайт фреймворка NestJS",
  "tags": [
    "nestjs",
    "documentation"
  ]
}


###

PATCH  http://localhost:3300/api/post/ab04593b-da99-4fe3-8b4b-e06d82e2efdd
Content-Type: application/json

{
  "text": "Test",
  "preview": "В этой публикации разберём основные возможности NestJS"
}