POST http://localhost:3300/api/post
Content-Type: application/json

{
  "typePost": "VIDEO",
  "title": "Очень интересное видео о разработке",
  "url": "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
  "tags": [
    "nestjs",
    "typescript",
    "backend"
  ]
}
###

GET http://localhost:3300/api/post


###
GET http://localhost:3300/api/post/ab04593b-da99-4fe3-8b4b-e06d82e2efdd
###
DELETE http://localhost:3300/api/post/6d308040-96a2-4162-bea6-2338e9976540

###
POST http://localhost:3300/api/post
Content-Type: application/json

{
 "typePost": "TEXT",
 "title": "Как правильно изучать NestJS",
  "preview": "В этой публикации разберём основные возможности NestJS и архитектуру серверного приложения.",
  "text": "NestJS предоставляет модульную архитектуру, dependency injection, контроллеры, providers, pipes, guards и interceptors. Благодаря этому приложение проще тестировать и расширять.",
  "tags": [
    "nestjs",
    "nodejs"
  ]
}

###
POST http://localhost:3300/api/post
Content-Type: application/json

{
  "typePost": "LINK",
  "link": "https://nestjs.com",
  "description": "Официальный сайт фреймворка NestJS",
  "tags": [
    "nestjs",
    "documentation"
  ]
}


###

PATCH  http://localhost:3300/api/post/f014c400-12a4-4584-abd2-41ce3e62ac13
Content-Type: application/json

{
  "link": "https://www.youtube.com/watch?v=aqz-KE-bpKQ",
  "description": "Тест"
}