# Create a new user
POST http://localhost:3300/api/auth/register
Content-Type: application/json

{
  "email": "vlad.stavros@bk.ru",
  "password": "Strong123!",
  "name": "Alex",
  "avatar": "image.png"
}
###


# Login
POST http://localhost:3300/api/auth/login
Content-Type: application/json

{
    "email": "vlad.stavros@bk.ru",
    "password": "Strong123!"
}

###

# Get User Data
GET http://localhost:3300/api/auth/6ab674d1dc9552ee2aee03c0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YWI2NzRkMWRjOTU1MmVlMmFlZTAzYzAiLCJlbWFpbCI6InZsYWQuc3RhdnJvc0Biay5ydSIsIm5hbWUiOiJBbGV4IiwiYXZhdGFyIjoiaW1hZ2UucG5nIiwiaWF0IjoxNzkwNDMzNzQ4LCJleHAiOjE3OTA0MzQ2NDh9.OSrxCc-saZsxYS27CJ4N0lNXANcDccInOJ_VuW9mFK0

###