services:
  readme-post.postgres:
    image: postgres:15-alpine
    restart: always
    env_file:
       - ./post.env
    container_name: readme-post.postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    
  readme-post.postgres.ui:
    image: dpage/pgadmin4:latest
    container_name: readme-post.postgres.ui
    depends_on:
      - readme-post.postgres
    restart: always
    ports:
      - "8082:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

volumes:
  postgres_data: